/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniHelloWorld */

#ifndef _Included_JniHelloWorld
#define _Included_JniHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniHelloWorld
 * Method:    displayHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniHelloWorld_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
